# Generated by Django 6.0 on 2026-02-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_parent_alter_comment_content_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reply', 'Reply'), ('like', 'Like')], default='reply', max_length=10),
        ),
    ]
